remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  
title: "Oshane O. Thomas, PhD"
description: "Biological Anthropologist | Researcher | Data Scientist"
url: "https://oothomas.github.io"
author:
  name: "Oshane O. Thomas"
  email: "oothomas07@gmail.com"
  links:
    - label: LinkedIn
      url: "https://www.linkedin.com/in/oshane-o-thomas"
