title: "Oshane O. Thomas, PhD"
description: "Biological Anthropologist | Researcher | Machine Learning Scientist"
url: "https://oothomas.github.io"
author: 
  name: "Oshane O. Thomas"
  email: "oothomas07@gmail.com"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/oshane-o-thomas"

remote_theme: pages-themes/modernist@v0.2.0

# Optional: If you plan on adding plugins or extra functionality, you can include them here.
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
