title: "Oshane O. Thomas, PhD"
description: "AI & Bioinformatics Scientist — Machine Learning for Medical Imaging & Morphology<br>Seattle, WA • On-site/Remote/Hybrid • <a href='mailto:oothomas07@gmail.com'>Gmail</a> • <a href='https://www.linkedin.com/in/oshane-o-thomas'>LinkedIn</a> • <a href='https://github.com/oothomas'>GitHub</a>"
url: "https://oothomas.github.io"
author:
  name: "Oshane O. Thomas"
  email: "oothomas07@gmail.com"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/oshane-o-thomas"

remote_theme: pages-themes/modernist@v0.2.0

# Optional: If you plan on adding plugins or extra functionality, you can include them here.
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
